### ISSUE TITLE
Update procedure?

### ISSUE THREAD

**Issue by rtech73** [DaveGut/TP-Link-SmartThings#15]
I have searched all the documentation and had trouble finding any clear path from the Cloud Connect to the new SmartThings Manager app.   I was able to set up and add my devices that would not add in the old app just fine (glad to get my dual plug finally on board!), but any device that is already in the old app will not install in the new.   What's the best way to update to the new app and DH's?   I have 44 devices in this situation, many tied to other apps, so I'm hoping I don't need to delete and reinstall the old devices!    Apologies if this isn't the best place to post this question!

**Comment by DaveGut** [comment]
Are all of the devices working now?  If so, give me some time to investigate how to automate the process better.  Some questions;

What is the FROM version?

How many devices are installed in the FROM version.

How many devices are installed in the new version.

Dave

**Comment by DaveGut** [comment]
I just updated the device handlers, smart application, read.me, and documentation for the integration.  I divided the tasks up so that knowledgeable persons can skip through the common steps while still providing details for the novice.

The new instructions include an update procedure and I also created an update method in the SmartApp to try to make it simpler.

Dave

**Comment by DaveGut** [comment]
Closing due to lack of return comments.  Previous post provided an updated driver/app set and the documentation has been updated to explicitly cover updates.
