### ISSUE TITLE
Error when updating TP_Link Smart Plug from 3.5.02 to 4.

### ISSUE THREAD

**Issue by ShaunTheBaa** [DaveGut/TP-Link-SmartThings#18]
When pasting contents of TP-Link Plug.groovy into my device handler TP-Link Smart Plug I get an error:

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script_dth_metadata_ddcf0d3f_a2d3_4527_8d29_d0e9610b1bc2: 230: expecting EOF, found 'Plug' @ line 230, column 9.
TP-Link Plug and Switch Device Handler, 2018, Version 3
^

1 error

**Comment by ShaunTheBaa** [comment]
Wait, nevermind. It seems that using Ctrl + A wasn't actually selecting all of the code in the device handler to paste over top of.

**Comment by ShaunTheBaa** [comment]
Impressive work by the way. To go from 1570 lines of code down to 756 lines in the service manager while adding more functionality is incredible.

**Comment by ShaunTheBaa** [comment]
@DaveGut 

Do you know if there is limitations or a recommendation over how many TP-Link device this smart app can handle? I am having a house built at the moment and it is going to be a full smart home with;

23 Tunable white bulbs
7 Multi Colour bulbs
7 Smart plugs

Would this smart app handle all of this? I haven't bought all of these devices yet and am trying to research what would be the best brand of device to use with smart-things, but haven't figured out which one yet. TP-Link devices are just across the road but Phillips hue or something other may work more natively.

**Comment by DaveGut** [comment]
Shaun,

**Question:**  What phone app are you using (IOS or android)?  One user reported a problem with IOS and the new app.

**Number of devices:**  I know of at least one 34 device installation with TP-Link Smart Things.

**TP-Link Devices**  A limited recommendation.  They have a very strong product line.  However, I can't support the Samsung platform migration to the new architecture (I am not a corporation and do not have the cloud assets).  That being said, Samsung has not announced a sunset for the classic IDE support and my integration (aside from installation of the smart app) works with the new phone app.

**Zigbee:**  There are a lot of these devices and they are coming out compatible with SmartThings, the new Alexa with a Zigbee transceiver, and Hubitat.  But, assure that any devices you get are verified with your platform (do a search on the SmartThings forum).  It reduces your risk.

**Smart Plugs:**  Rather than Smart Plugs, why not use Outlets for some of the installations.  Have the electrician install the smart outlets instead of using smart plugs.  (Usually, these control only one of the two outlets, you may still need some plugs.)  TP-Link is about to release a dual-controlled Smart Outlet, there may be others.

**Smart Switches:**  I did not see any on your list.  I use these to control on-off and dimming for overhead fixtures with multiple bulbs or single fans.

**Comment by DaveGut** [comment]
Closing due to lack of return comments.  Previous post provided an updated driver/app set and the documentation has been updated to explicitly cover updates.

**Comment by DaveGut** [comment]
Closing due to lack of return comments.  Previous post provided an updated driver/app set and the documentation has been updated to explicitly cover updates.
